language: csharp
solution: OctoGhast.sln
install:
  - nuget restore OctoGhast.sln
script:
  - xbuild OctoGhast.sln /p:TargetFrameworkVersion="v4.5"
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master
