namespace RenderLike
{
    /// <summary>
    /// Special compatiability enumeration for libtcod.
    /// </summary>
    public enum TCODSpecialCharacter
    {
        Smilie = 1,
        SmilieInv = 2,
        Heart = 3,
        Diamond = 4,
        Club = 5,
        Spade = 6,
        Bullet = 7,
        BulletInv = 8,
        Male = 11,
        Female = 12,
        Note = 13,
        NoteDouble = 14,
        Light = 15,
        ArrowEastNoTail = 16,
        ArrowWestNoTail = 17,
        DoubleArrowVert = 18,
        ExclamationDouble = 19,
        Pilcrow = 20,
        Section = 21,
        ArrowNorth = 24,
        ArrowSouth = 25,
        ArrowEast = 26,
        ArrowWest = 27,
        DoubleArrowHorz = 29,
        ArrowNorthNoTail = 30,
        ArrowSouthNoTail = 31,
        Pound = 156,
        Multiplication = 158,
        Function = 159,
        Reserved = 169,
        Half = 171,
        OneQuarter = 172,
        Block1 = 176,
        Block2 = 177,
        Block3 = 178,
        VertLine = 179,
        TeeWest = 180,
        Copyright = 184,
        DoubleTeeWest = 185,
        DoubleVertLine = 186,
        DoubleNE = 187,
        DoubleSE = 188,
        Cent = 189,
        Yen = 190,
        NE = 191,
        SW = 192,
        TeeNorth = 193,
        TeeSouth = 194,
        TeeEast = 195,
        HorzLine = 196,
        Cross = 197,
        DoubleSW = 200,
        DoubleNW = 201,
        DoubleTeeNorth = 202,
        DoubleTeeSouth = 203,
        DoubleTeeEast = 204,
        DoubleHorzLine = 205,
        DoubleCross = 206,
        Currency = 207,
        SE = 217,
        NW = 218,
        SubpixelNorthWest = 226,
        SubpixelNorthEast = 227,
        SubpixelNorth = 228,
        SubpixelSoutheast = 229,
        SubpixelDiagonal = 230,
        SubpixelEast = 231,
        SubpixelSouthwest = 232,
        ThreeQuarters = 243,
        Division = 246,
        Grade = 248,
        Umlaut = 249,
        Pow1 = 251,
        Pow3 = 252,
        Pow2 = 253,
        BulletSquare = 254
    }
}